#!/bin/bash

SPOOL=/var/spool/usbip/attach

if [[ $1 == "-q" ]]
then
    exec &>/dev/null
fi

touch $SPOOL

while [[ -e $SPOOL ]]
do
    /usr/sbin/usbip attach -r 192.168.1.1 -b 1-1.3 # Modify USB port and ip
    sleep 10
done

/usr/sbin/usbip detach -p 0

exit 0
